apiVersion: v1
kind: Service
metadata:
  name: confluence
  namespace: confluence
  annotations:
    # Https offloading to ilb
    #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ARN_TO_CERT
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: confluence
  ports:
  - name: https
    port: 443
    #port: 8090
    targetPort: 8090
  type: LoadBalancer

